include(${CMAKE_CURRENT_LIST_DIR}/SDL3Subsystems.cmake)
set(ENV{ANDROID_HOME} /opt/android-sdk)
set(ANDROID_ABI arm64-v8a)
set(ANDROID_PLATFORM 21)
include(/opt/android-ndk/build/cmake/android.toolchain.cmake)
set(CMAKE_FIND_ROOT_PATH /opt/android-libs/aarch64)
include_directories(SYSTEM ${CMAKE_FIND_ROOT_PATH}/include)
set(CMAKE_INSTALL_PREFIX /opt/android-libs/aarch64 CACHE PATH "" FORCE)
