include(${CMAKE_CURRENT_LIST_DIR}/SDL3Subsystems.cmake)
set(ANDROID_ABI x86_64)
set(ANDROID_PLATFORM 21)
include(/opt/android-ndk/build/cmake/android.toolchain.cmake)
set(CMAKE_FIND_ROOT_PATH /opt/android-libs/x86-64)
include_directories(SYSTEM ${CMAKE_FIND_ROOT_PATH}/include)
set(CMAKE_INSTALL_PREFIX /opt/android-libs/x86-64 CACHE PATH "" FORCE)
