name: GTest

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install prerequisites
        run: pacman -Syu --noconfirm cmake ninja clang lld sdl3 gtest valgrind

      - name: Configure CMake
        run: cmake --preset x86_64-linux-gnu-release

      - name: Build examples
        run: cmake --build build/x86_64-linux-gnu/release -t examples

      - name: Build tests
        run: cmake --build build/x86_64-linux-gnu/release -t tests

      - name: Run tests
        run: env DEBUGINFOD_URLS=https://debuginfod.archlinux.org valgrind ctest --test-dir build/x86_64-linux-gnu/release
